{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-backoffice.container-secret") -}}
{{- define "ffc-ahwr-backoffice.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
{{- end -}}
