{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-backoffice.container-secret") -}}
{{- define "ffc-ahwr-backoffice.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  {{- if .Values.azureAppRegistration.enabled }}
  AADAR_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AADAR_CLIENT_ID: {{ quote .Values.azureAppRegistration.clientId }}
  AADAR_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
