{{- include "ffc-helm-library.deployment" (list . "ffc-ahwr-backoffice.deployment") -}}
{{- define "ffc-ahwr-backoffice.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-ahwr-backoffice.container") }}
{{- end -}}
