# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-backoffice:
    build:
      target: development
    image: ffc-ahwr-backoffice-development
    container_name: ffc-ahwr-backoffice-development
    environment:
      USE_PRETTY_PRINT: ${USE_PRETTY_PRINT:-true}
      SUPER_ADMINS: ${SUPER_ADMINS:-developer@defra.gov.uk}
    ports:
      - "3002:3000"
      - "9231:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

volumes:
  redis_data:
