services:
  ffc-ahwr-backoffice:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-backoffice-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: zaproxy/zap-bare:2.16.1
    command: zap.sh -cmd -quickurl http://ffc-ahwr-backoffice:${PORT:-3000} -configfile wrk/config/zap.conf -quickout wrk/test-output/zap-report.html
    depends_on:
      - ffc-ahwr-backoffice
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/
