version: '3.9'

services:
  ffc-ahwr-backoffice:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-backoffice-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: owasp/zap2docker-stable:2.14.0
    command: echo 12345
    depends_on:
      - ffc-ahwr-backoffice
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/