version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-backoffice:
    build:
      target: development
    image: ffc-ahwr-backoffice-development
    container_name: ffc-ahwr-backoffice-development
    ports:
      - "3002:3000"
      - "9231:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-backoffice-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.16.0
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
      - "10001:10001"
    command: "azurite --loose --skipApiVersionCheck --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

volumes:
  redis_data:
