version: '3.8'

services:
  ffc-ahwr-backoffice:
    build:
      context: .
      target: production
    image: ffc-ahwr-backoffice
    container_name: ffc-ahwr-backoffice
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-backoffice-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      AADAR_ENABLED: ${AADAR_ENABLED:-true}
      AADAR_CLIENT_SECRET: ${AADAR_CLIENT_SECRET:-notset}
      AADAR_CLIENT_ID: ${AADAR_CLIENT_ID:-notset}
      AADAR_REDIRECT_URL: ${AADAR_REDIRECT_URL:-http://localhost:3002/authenticate}
      AADAR_TENANT_ID: ${AADAR_TENANT_ID:-notset}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SERVICE_URI: http://localhost:3002
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      DISPLAY_PAGE_SIZE: 20
