environment: development
name: ffc-ahwr-backoffice
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-backoffice

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

azureAppRegistration:
  enabled: true
  clientId:
  clientSecret:
  redirectUrl:
  tenantId:

containerConfigMap:
  name: ffc-ahwr-backoffice-config-map

containerSecret:
  name: ffc-ahwr-backoffice-container-secret
  type: Opaque

container:
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  imagePullPolicy: IfNotPresent
  limitCpu: 120m
  limitMemory: 200Mi
  port: 3000
  requestCpu: 100m
  requestMemory: 200Mi
  redisHostname: redis-hostname.default
  redisPartition: ffc-ahwr-backoffice
  redisPassword: redis
  redisPort: 6379
  serviceUri:
  applicationApiUri:
  displayPageSize: 20
  dateOfTestingEnabled:
  onHoldAppProcessEnabled:
  onHoldAppProcessSchedule:
  endemicsEnabled:

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

ingress:
  class: nginx
  endpoint: ffc-ahwr-backoffice
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

service:
  port: 80
  type: ClusterIP
