environment: development
name: ffc-ahwr-backoffice
namespace: ffc-demo
workstream: ffc-demo
image: ffc-ahwr-backoffice

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-ahwr-backoffice-config-map

containerSecret:
  name: ffc-ahwr-backoffice-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  backOfficeRequestQueueAddress: ffc-ahwr-backoffice-request
  backOfficeResponseQueueAddress: ffc-ahwr-backoffice-response
  azureStorageConnectionString:
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  imagePullPolicy: IfNotPresent
  limitCpu: 120m
  limitMemory: 200Mi
  messageQueueHost: namespace.servicebus.windows.net
  port: 3000
  requestCpu: 100m
  requestMemory: 200Mi
  redisHostname: redis-hostname.default
  redisPartition: ffc-ahwr-backoffice
  redisPassword: redis
  redisPort: 6379
  serviceUri:

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
